import 'package:animus/ui/storage/widgets/pages/library_folder_screen/folder_available_analysis_picker/folder_available_analysis_picker_view.dart';

typedef FolderAvailableAnalysisPicker = FolderAvailableAnalysisPickerView;
