import 'package:animus/ui/intake/widgets/pages/second_instance_analysis_screen/second_instance_decision_card/second_instance_decision_card_view.dart';

typedef SecondInstanceDecisionCard = SecondInstanceDecisionCardView;
