#!/usr/bin/env sh

commit_msg_file="$1"
commit_msg="$(cat "$commit_msg_file")"

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert): ANI-[0-9]+ .+'

if ! printf '%s' "$commit_msg" | grep -Eq "$pattern"; then
	echo '⛔ Invalid commit message format.'
	echo 'Expected: <type>: ANI-{number} <description>'
	echo 'Example: feat: ANI-25 add login screen'
	exit 1
fi

npx --no -- commitlint --edit "$commit_msg_file"
